# Generated by Django 2.1.1 on 2018-09-13 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 13, 22, 44, 46, 59068, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
